export const LOADING = 'LOADING';
export const ALL_POKEMON = 'ALL_POKEMON';
export const TOTAL_COUNT = 'TOTAL_COUNT';
export const ALL_POKEMON_SUCCESS = 'ALL_POKEMON_SUCCESS';
export const SINGLE_POKEMON_SUCCESS = 'SINGLE_POKEMON_SUCCESS';
